In [ ]:
list1=[1,2,3,4]

In [ ]:
import numpy as np

Traceback (most recent call last):
  File "/Users/eunu/.vscode/extensions/ms-python.python-2025.18.0-darwin-arm64/python_files/python_server.py", line 134, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'



In [ ]:
arr1= np.array(list1)

In [ ]:
arr1

[1 2 3 4]


In [ ]:
array([1,2,3,4])


Traceback (most recent call last):
  File "/Users/eunu/.vscode/extensions/ms-python.python-2025.18.0-darwin-arm64/python_files/python_server.py", line 134, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
NameError: name 'array' is not defined. Did you mean: 'arr1'? Or did you forget to import 'array'?



In [ ]:
arr2=np.array([2,3,4,5,5])

In [ ]:
arr2

[2 3 4 5 5]


In [ ]:
import numpy as dd

In [ ]:
list1=[1,2,3,'sam',True]


In [ ]:
list1

[1, 2, 3, 'sam', True]


In [ ]:
arr1=

In [ ]:
arr1=dd.array(list1)

Traceback (most recent call last):
  File "/Users/eunu/.vscode/extensions/ms-python.python-2025.18.0-darwin-arm64/python_files/python_server.py", line 134, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/numpy/__init__.py", line 795, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {attr!r}")
AttributeError: module 'numpy' has no attribute 'arrary'. Did you mean: 'array'?



In [ ]:
arr1

['1' '2' '3' 'sam' 'True']


In [ ]:
arr2=np.array([1,2,3,4,5,5,25)])

Traceback (most recent call last):
  File "/Users/eunu/.vscode/extensions/ms-python.python-2025.18.0-darwin-arm64/python_files/python_server.py", line 134, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1
    arr2=np.array([1,2,3,4,5,5,25)])
                                 ^
SyntaxError: closing parenthesis ')' does not match opening parenthesis '['



In [ ]:
arr2

[2 3 4 5 5]


In [ ]:
type(arr2)

<class 'numpy.ndarray'>


In [ ]:
arr3=dd.array([1,2,3,True])

In [ ]:
arr3

[1 2 3 1]


In [ ]:
arr4=np.array([1,2,3,True,False])


In [ ]:
arr4

[1 2 3 1 0]


In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1])

In [ ]:
arr1

[1]


In [ ]:
arr1.ndim

1


In [ ]:
arr1.shape

(1,)


In [ ]:
arr1.size

1


In [ ]:
arr2 = np.array([1,2])

In [ ]:
arr2.ndim

1


In [ ]:
arr2.shape

(2,)


In [ ]:
arr2.size

2


In [ ]:
arr3=np.array([1,2,3,4])

In [ ]:
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)

1
(4,)
4


In [ ]:
arr4=np.array([[1,2],[3,4]])

In [ ]:
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

2
(2, 2)
4


In [ ]:
arr5=np.array([[1,2,3],[1,2,3]])

In [ ]:
arr5


[[1 2 3]
 [1 2 3]]


In [ ]:
arr6=np.array([[1],[2],[3],[4]])

In [ ]:
print(arr6.ndim)
print(arr6.shape)
print(arr6.size)

2
(4, 1)
4


In [ ]:
arr7=np.array([[[1,2],[1,2],[1,2]],[[1,2],[1,2],[1,2]]])

Traceback (most recent call last):
  File "/Users/eunu/.vscode/extensions/ms-python.python-2025.18.0-darwin-arm64/python_files/python_server.py", line 134, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
TypeError: Field elements must be 2- or 3-tuples, got '[1, 2]'



In [ ]:
arr7

[[[1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]]]


In [ ]:
print(arr7.ndim)
print(arr7.shape)
print(arr7.size)

3
(2, 3, 2)
12


In [ ]:
arr8=np.array([[[1],[1]],[[1],[1]],[[1],[1]],[[1],[1]],[[1],[1]]])

In [ ]:
arr8

[[[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]]


In [ ]:
arr9=np.array([[[[[1],[1]],[[1],[1]],[[1],[1]] ]]])

Traceback (most recent call last):
  File "/Users/eunu/.vscode/extensions/ms-python.python-2025.18.0-darwin-arm64/python_files/python_server.py", line 134, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
TypeError: 'builtin_function_or_method' object is not subscriptable



In [ ]:
arr9

[[[[[1], [1]], [[1], [1]], [[1], [1]]]]]


In [ ]:
print(arr9.ndim)
print(arr9.shape)
print(arr9.size)

5
(1, 1, 3, 2, 1)
6


In [ ]:
arr10=np.array([[[[[1], [1]], [[1], [1]], [[1], [1]]]]],[[[[[1], [1]], [[1], [1]], [[1], [1]]]]])

Traceback (most recent call last):
  File "/Users/eunu/.vscode/extensions/ms-python.python-2025.18.0-darwin-arm64/python_files/python_server.py", line 134, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
TypeError: Field elements must be 2- or 3-tuples, got '[[[[1], [1]], [[1], [1]], [[1], [1]]]]'



In [ ]:
print(arr10.ndim)
print(arr10.shape)
print(arr10.size)

Traceback (most recent call last):
  File "/Users/eunu/.vscode/extensions/ms-python.python-2025.18.0-darwin-arm64/python_files/python_server.py", line 134, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
NameError: name 'arr10' is not defined. Did you mean: 'arr1'?



In [ ]:
arr1=np.array([10,20,30,40,50,60,70     ])

In [ ]:
arr1

[10 20 30 40 50 60 70]


In [ ]:
arr1[0]

10


In [ ]:
arr1[4]

50


In [ ]:
arr1

[10 20 30 40 50 60 70]


In [ ]:
arr1[-1]

70


In [ ]:
arr2[-2]

1


In [ ]:
arr1[-3]

50


In [ ]:
arr1[-5]

30


In [ ]:
arr1

[10 20 30 40 50 60 70]


In [ ]:
arr1[0:3]

[10 20 30]


In [ ]:
arr1[1:3]

[20 30]


In [ ]:
arr1[:]

[10 20 30 40 50 60 70]


In [ ]:
arr1[0:]

[10 20 30 40 50 60 70]


In [ ]:
arr1[:3]

[10 20 30]


In [ ]:
arr1[:-1]

[10 20 30 40 50 60]


In [ ]:
arr1[-5:-2]

[30 40 50]


In [ ]:
arr1[::1]

[10 20 30 40 50 60 70]


In [ ]:
arr1[::4]

[10 50]


In [ ]:
arr1[::3]

[10 40 70]


In [ ]:
arr1[::-1]

[70 60 50 40 30 20 10]


In [ ]:
arr1[::-2]

[70 50 30 10]


In [ ]:
arr1[::-3]

[70 40 10]


In [ ]:
arr1[-2::-1]

[60 50 40 30 20 10]


In [ ]:
arr1

[10 20 30 40 50 60 70]


In [ ]:
l1=[1,4]

In [ ]:
arr1[l1]

[20 50]


In [ ]:
arr1[6]

70
